{{- if .Values.model.pullEnabled }}
{{- $models := .Values.model.names | default (list .Values.model.name) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-pull-model
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        {{- include "ollama.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pull-model
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - |
              until ollama list >/dev/null 2>&1; do
                echo "waiting for ollama service to become ready..."
                sleep 5
              done
              for model in {{ join " " $models }}; do
                ollama pull "$model";
              done
          env:
            - name: OLLAMA_HOST
              value: "http://{{ .Values.name }}:{{ .Values.service.port }}"
{{- end }}
