name: ollama
namespace: finagent-dbs
image:
  repository: ollama/ollama
  tag: "0.6.5"
  pullPolicy: IfNotPresent
service:
  port: 11434
storage:
  accessMode: ReadWriteOnce
  className: finagent-nfs
  size: 30Gi
model:
  pullEnabled: true
  name: llama3.2:3b
  names:
    - llama3.2:3b
resources:
  requests:
    cpu: "2"
    memory: 4Gi
  limits:
    cpu: "6"
    memory: 10Gi
nodeSelector:
  kubernetes.io/hostname: ip-10-0-0-190
tolerations:
  - key: ollama
    operator: Equal
    value: "true"
    effect: NoExecute
