kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: admin
    persistence:
      enabled: true
      type: pvc
      storageClassName: finagent-nfs
      accessModes:
        - ReadWriteMany
      size: 10Gi

    additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        isDefault: false
        jsonData:
          maxLines: 1000
          timeout: 60
        editable: true

    service:
      type: ClusterIP

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: finagent-nfs
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 20Gi

  alertmanager:
    enabled: true
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: finagent-nfs
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 10Gi


# =========================
# GATEWAY CONFIG (UNCHANGED)
# =========================

httpRoute:
  enabled: true
  name: prometheus-grafana-route

  gateway:
    name: finagent-gateway
    namespace: finagent-gateway-ns

  hostname: grafana.nexaflow.site

  path:
    type: PathPrefix
    value: /

  urlRewrite:
    enabled: false
    replacePrefixMatch: /

  backend:
    name: prometheus-stack-grafana
    port: 80
