apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finagent-expense-service-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nexaflow-org/nexaflow-helm.git
    targetRevision: main
    path: apps/test/finagent-expense-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: finagent-apps-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
