global:
  defaultStorageClass: finagent-nfs

keycloak:
  production: true
  proxyHeaders: xforwarded
  httpEnabled: true
  cache:
    enabled: false

  image:
    registry: docker.io
    repository: bitnamilegacy/keycloak
    tag: 26.3.3-debian-12-r0

  auth:
    adminUser: admin
    adminPassword: "ChangeMe-Admin-Password-Immediately"

  service:
    type: ClusterIP
    http:
      enabled: true

  ingress:
    enabled: false

  tls:
    enabled: false

  replicaCount: 1

  resourcesPreset: small

  extraEnvVars:
    - name: KC_HOSTNAME
      value: https://keyclaok.myfinagent.online
    - name: KC_HOSTNAME_STRICT
      value: "true"
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_PROXY_HEADERS
      value: xforwarded

  postgresql:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql
      tag: 17.6.0-debian-12-r0
    auth:
      postgresPassword: "ChangeMe-Postgres-Admin-Password-Immediately"
      username: bn_keycloak
      password: "ChangeMe-Keycloak-DB-Password-Immediately"
      database: bitnami_keycloak
    primary:
      persistence:
        enabled: true
        storageClass: finagent-nfs
        size: 8Gi

httpRoute:
  enabled: true
  name: keycloak-route
  namespace: keycloak
  hostname: keyclaok.myfinagent.online
  gateway:
    name: finagent-gateway
    namespace: finagent-gateway-ns
  path:
    type: PathPrefix
    value: /
  backend:
    name: keycloak
    port: 80
