apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "finagent-mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | quote }}
  AUTH_MYSQL_DATABASE: {{ .Values.secret.AUTH_MYSQL_DATABASE | quote }}
  AUTH_MYSQL_USER: {{ .Values.secret.AUTH_MYSQL_USER | quote }}
  AUTH_MYSQL_PASSWORD: {{ .Values.secret.AUTH_MYSQL_PASSWORD | quote }}
  EXPENSE_MYSQL_DATABASE: {{ .Values.secret.EXPENSE_MYSQL_DATABASE | quote }}
  EXPENSE_MYSQL_USER: {{ .Values.secret.EXPENSE_MYSQL_USER | quote }}
  EXPENSE_MYSQL_PASSWORD: {{ .Values.secret.EXPENSE_MYSQL_PASSWORD | quote }}
