apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "finagent-mysql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "finagent-mysql.selectorLabels" . | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
