name: finagent-mysql
namespace: finagent-dbs
appsNamespace: finagent-apps
image:
  repository: mysql
  tag: "8.4"
  pullPolicy: IfNotPresent
service:
  port: 3306
storage:
  accessMode: ReadWriteOnce
  className: finagent-nfs
  size: 3Gi
config:
  MYSQL_DATABASE_PLACEHOLDER: bootstrap
  MYSQL_CHARSET: utf8mb4
  MYSQL_COLLATION: utf8mb4_unicode_ci
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "200m"
    memory: 512Mi
